# Generated by Django 4.2.7 on 2025-11-07 00:48

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food spot', max_length=200)),
                ('cuisine_type', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('american', 'American'), ('fast_food', 'Fast Food'), ('cafe', 'Cafe/Coffee Shop'), ('pizza', 'Pizza'), ('burger', 'Burgers'), ('seafood', 'Seafood'), ('vegetarian', 'Vegetarian/Vegan'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('other', 'Other')], default='other', help_text='Type of cuisine offered', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description')),
                ('address', models.CharField(help_text='Street address', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Rating out of 5', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('price_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=10)),
                ('opening_hours', models.CharField(default='9:00 AM - 10:00 PM', help_text='Operating hours', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location (longitude, latitude)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['cuisine_type'], name='locations_f_cuisine_c1c601_idx'), models.Index(fields=['rating'], name='locations_f_rating_4522a9_idx')],
            },
        ),
    ]
