# Generated by Django 4.2.7 on 2025-11-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodspot',
            name='price_range',
            field=models.CharField(choices=[('€', 'Budget (€)'), ('€€', 'Moderate (€€)'), ('€€€', 'Expensive (€€€)'), ('€€€€', 'Very Expensive (€€€€)')], default='€€', max_length=10),
        ),
    ]
