# Generated by Django 4.2.7 on 2025-12-08 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_foodspot_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Name of the reviewer', max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, help_text='Email of the reviewer (optional)', max_length=254, null=True)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(help_text='Review comment', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the review is approved and visible')),
                ('foodspot', models.ForeignKey(help_text='The food spot being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='locations.foodspot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['foodspot', '-created_at'], name='locations_r_foodspo_196ca2_idx'), models.Index(fields=['rating'], name='locations_r_rating_95e197_idx')],
            },
        ),
    ]
